# Generated by Django 4.2.23 on 2025-06-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('submiter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('submiter_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('submiter_email', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='prayer.prayercategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
