# Generated by Django 4.2.23 on 2025-06-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdemand',
            old_name='status',
            new_name='state',
        ),
    ]
