# Generated by Django 4.2.23 on 2025-06-21 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='person',
            field=models.ForeignKey(blank=True, help_text='The person responsible for this program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
