# Generated by Django 4.2.23 on 2025-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
