# Generated by Django 4.2.23 on 2025-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_rdv_date_rdv_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='time',
        ),
        migrations.AddField(
            model_name='rdv',
            name='informations',
            field=models.TextField(default=''),
        ),
    ]
