# Generated by Django 4.2.23 on 2025-06-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0003_remove_rdv_time_rdv_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rdvavailability',
            name='user',
        ),
    ]
