# Generated by Django 4.2.23 on 2025-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0004_remove_rdv_user_remove_rdvavailability_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdvavailability',
            name='end_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rdvavailability',
            name='start_time',
            field=models.CharField(max_length=200),
        ),
    ]
