# Generated by Django 4.2.23 on 2025-06-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0005_alter_rdvavailability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
